<?php
/**
 * This file is part of YAPEPBase.
 *
 * @package    YapepBaseTest
 * @subpackage Syslog
 * @copyright  2011 The YAPEP Project All rights reserved.
 * @license    http://www.opensource.org/licenses/bsd-license.php BSD License
 */

namespace YapepBaseTest\Syslog;


use YapepBase\Syslog\Syslog;

use YapepBaseTest\Mock\Syslog\SyslogConnectionMock;

/**
 * Test class for SyslogConnectionAbstract.
 * Generated by PHPUnit on 2011-12-06 at 11:33:00.
 */
class SyslogConnectionTest extends \YapepBaseTest\TestAbstract {
	/**
	 * @var SyslogConnectionMock
	 */
	protected $object;

	public function setUp() {
		parent::setUp();
		$this->object = new SyslogConnectionMock();
	}

	public function testExceptionConversion() {
		$this->object->setExceptions(true);
		$this->assertFalse($this->object->openlog('test', 0, Syslog::LOG_USER));
		$this->assertFalse($this->object->syslog(Syslog::LOG_NOTICE, 'test'));
		$this->assertFalse($this->object->closelog());
	}
}